### ISSUE TITLE
Support .NET 4.0 by using mutil target frameworks

### ISSUE THREAD

**Issue by ArcticLampyrid** [oleg-shilo/cs-script.core#2]

**Comment by ArcticLampyrid** [comment]
It's useful when you are developing a library (needs to support both .NET Core and .NET 4.0) depending on "cs-script"

**Comment by oleg-shilo** [comment]
It already does. The nuget package "CS-Script.Core" delivers the assembly (CSSCriptLib.dll) compiled for .NET Standard just out of box:

![image](https://user-images.githubusercontent.com/16729806/56468904-f2dc8400-6475-11e9-89a0-d1023ca5456d.png)

The name of the repository "CS-Script.Core" does reflect the fact that this edition of CS-Script is designed to utilize new features available on .NET Core (e.g. C# 6+ syntax, built in Roslyn compilers). 

But this does not imply that the CS-Script class library and the executable can only be hosted by .NET Core runtime.

**Comment by ArcticLampyrid** [comment]
.NET Standard 2.0 is not compatible with .NET 4.0 (require .NET 4.6)
.NET 4.0 is the last version compatible with XP. Although XP should be abandoned, there are still some users who are using it

**Comment by oleg-shilo** [comment]
Yes, of course not all versions of .NET Full are compatible with `netstandard2`. 
That's why there is a pure .NET Full nuget package available.

Kind of "if you use legacy host then you should use legacy script engine".

You may want to use `cs-script` (or `cs-script.lib`) package for .NET full and `cs-script.core` for .NET Core projects. I see no other way unless I am missing something.
