### ISSUE TITLE
.net core 3 migration

### ISSUE THREAD

**Issue by rumen-yankov** [oleg-shilo/cs-script.core#5]
Hello Oleg, 
this is continuation of the ticket i submitted for cs-script project https://github.com/oleg-shilo/cs-script/issues/176. 

The problem is very specific, It only appear when project type is Razor library and use  additional dependencies. Changing your sample working project file to one in attached sample leads to exception i get in my project. 

[ConsoleApp.zip](https://github.com/oleg-shilo/cs-script.core/files/3694883/ConsoleApp.zip)

**Comment by oleg-shilo** [comment]
OK, it is an interesting problem. 
After dissecting it I found that it is not CS-Script but a generic assembly referencing problem. And problem is not even related to the project type (e.g. Razor). Thus a normal SDK project with this single line of code would exhibit the same problem:
```C#
static void Main(string[] args)
{
    var options = Microsoft.CodeAnalysis.Scripting.ScriptOptions.Default;
}
```
The cause is incomplete Roslyn assemblies set. You are missing  "Microsoft.CodeAnalysis.CSharp.Scripting" package. This is how your project should look like:
 
```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CS-Script.Core" Version="1.2.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="3.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.3.1" />
  </ItemGroup>

</Project>
```

**Comment by rumen-yankov** [comment]
Thanks. Problem resolved.
